# Generated by Django 4.0.4 on 2022-05-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transf_loc', models.CharField(max_length=20)),
                ('sku', models.PositiveIntegerField()),
                ('primary_voltage', models.CharField(max_length=20)),
            ],
        ),
    ]
